# Generated by Django 4.2.8 on 2024-02-06 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_booking_rating_alter_booking_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='HealthAssistant_id',
        ),
        migrations.DeleteModel(
            name='HealthAssistant',
        ),
    ]
